/*
Navicat MySQL Data Transfer

Source Server         : test
Source Server Version : 50616
Source Host           : localhost:3306
Source Database       : test

Target Server Type    : MYSQL
Target Server Version : 50616
File Encoding         : 65001

Date: 2016-12-08 10:59:50
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `t_history_task`
-- ----------------------------
DROP TABLE IF EXISTS `t_history_task`;
CREATE TABLE `t_history_task` (
  `id` int(32) unsigned NOT NULL AUTO_INCREMENT,
  `taskid` varchar(64) NOT NULL,
  `submit_time` varchar(32) NOT NULL,
  `finish_time` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `data_source` varchar(64) NOT NULL,
  `query_info` varchar(1024) NOT NULL,
  `hql` varchar(2048) NOT NULL,
  `output_path` varchar(256) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `task_id` (`taskid`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of t_history_task
-- ----------------------------
INSERT INTO `t_history_task` VALUES ('1', 't_daily_user_1481012453847', '2016-12-06 16:20:53', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('2', 't_daily_user_1481012459729', '2016-12-06 16:20:59', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('3', 't_daily_user_1481012462393', '2016-12-06 16:21:02', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('4', 't_daily_user_1481119181353', '2016-12-07 21:59:41', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('5', 't_daily_user_1481119188921', '2016-12-07 21:59:48', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('6', 't_daily_user_1481119189816', '2016-12-07 21:59:49', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('7', 't_daily_user_1481119190476', '2016-12-07 21:59:50', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('8', 't_daily_user_1481119191288', '2016-12-07 21:59:51', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('9', 't_daily_user_1481119300196', '2016-12-07 22:01:40', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('10', 't_daily_user_1481119302832', '2016-12-07 22:01:42', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('11', 't_daily_user_1481119403990', '2016-12-07 22:03:23', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('12', 't_daily_user_1481119950002', '2016-12-07 22:12:30', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('13', 't_daily_user_1481119953488', '2016-12-07 22:12:33', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('14', 't_daily_user_1481120164767', '2016-12-07 22:16:04', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('15', 't_daily_user_1481120218149', '2016-12-07 22:16:58', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
INSERT INTO `t_history_task` VALUES ('16', 't_daily_user_1481120226697', '2016-12-07 22:17:06', '0000-00-00 00:00:00', 'ACCEPTED', 't_daily_user', '{\"start_time\":\"2016-11-15 00:00:00\",\"end_time\":\"2016-12-06 00:00:00\",\"dimensions\":{\"product_id\":\"1\",\"config_id\":\"all\",\"content_type\":\"all\",\"protocol\":\"https\",\"promotion\":\"all\",\"scenario\":\"all\",\"scenario_channel\":\"all\",\"strategy\":\"all\",\"language\":\"all\",\"app_ver\":\"all\"},\"metrics\":[\"total_request\",\"total_request_user\"]}', 'select product_id,config_id,content_type,protocol,promotion,scenario,scenario_channel,strategy,language,app_ver,total_request,total_request_user from t_daily_user where date between \"2016-11-15\" and \"2016-12-06\" and product_id=\"1\" and config_id=\"all\" and content_type=\"all\" and protocol=\"https\" and promotion=\"all\" and scenario=\"all\" and scenario_channel=\"all\" and strategy=\"all\" and language=\"all\" and app_ver=\"all\";', 'NULL');
