/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.inveno.feeder.thrift;

public enum Status implements org.apache.thrift.TEnum {
  YES(0),	// key不存在
  NO(1),	// key存在
  NO_RESPONSE(2),	// 服务器内部错误
  UNKNOW(3),	// 服务器内部错误
  GT1000(4);	// 批量请求的key超过1000个

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Status findByValue(int value) { 
    switch (value) {
      case 0:
        return YES;
      case 1:
        return NO;
      case 2:
        return NO_RESPONSE;
      case 3:
        return UNKNOW;
      case 4:
        return GT1000;
      default:
        return null;
    }
  }
}
